/**
 * generated by Xtext 2.20.0
 */
package guido.dsl.ide;

import guido.dsl.ide.AbstractDslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class DslIdeModule extends AbstractDslIdeModule {
}
